# Generated by Django 3.2.13 on 2023-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DC_Finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='resource',
            name='Project_number',
            field=models.CharField(blank=True, choices=[('Project Manager', 'Project Manager'), ('Principal Investigator', 'Principal Investigator'), ('Project Co-ordinator', 'Project Co-ordinator'), ('Research Assistant', 'Research Assistant'), ('Research Associate', 'Research Associate')], max_length=30, null=True),
        ),
    ]
