# Generated by Django 3.2.13 on 2023-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DC_Finance', '0002_auto_20230130_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='Resource_name',
        ),
        migrations.AlterField(
            model_name='resource',
            name='Project_number',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='Resource_select',
            field=models.CharField(blank=True, choices=[('FACULTY', 'FACULTY'), ('STUDENT', 'STUDENT')], max_length=30, null=True),
        ),
    ]
