# Generated by Django 3.2.13 on 2023-01-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DC_Finance', '0003_auto_20230130_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Resource_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.faculty'),
        ),
    ]
