# Generated by Django 3.2.13 on 2023-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DC_Finance', '0004_resource_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Resource_name',
            field=models.CharField(max_length=30),
        ),
    ]
