# Generated by Django 3.2.15 on 2022-11-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FACULTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professor_Name', models.CharField(max_length=20)),
                ('ID_Number', models.CharField(max_length=20)),
                ('Internship_Supervisor', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('External_Principal_Investigator', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Research_Associate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('External_Research_Assistant', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Administration_Support_Staff', models.CharField(max_length=20)),
                ('Post_Doc', models.CharField(max_length=20)),
                ('Technician_Name', models.CharField(max_length=20)),
                ('Contract_hours', models.IntegerField()),
                ('Faculty_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.department')),
            ],
        ),
        migrations.CreateModel(
            name='FISCAL_YEAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fiscal_Year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=60)),
                ('Project_number', models.CharField(max_length=15)),
                ('Project_Manager', models.CharField(max_length=20)),
                ('Count_as_Project', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Start_this_Fiscal', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Fiscal_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.fiscal_year')),
                ('Professor_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='PROJECT_PARTNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Partner', models.CharField(max_length=20)),
                ('Project_Partner_NAICS_Classification', models.CharField(max_length=50)),
                ('Project_Partner_Size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RESEARCH_CENTRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research_Centre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=20)),
                ('International_Student', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Student_Number', models.IntegerField()),
                ('Contract_Hours', models.IntegerField()),
                ('Fiscal_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.fiscal_year')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.program')),
                ('Project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project')),
                ('Research_Centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.research_centre')),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_start_date', models.DateTimeField()),
                ('Project_end_date', models.DateTimeField()),
                ('Business_solution', models.CharField(max_length=20)),
                ('Project_outcome', models.TextField()),
                ('Success_Story_Produced', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Project_Partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project_partner'),
        ),
        migrations.AddField(
            model_name='project',
            name='Research_Centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.research_centre'),
        ),
        migrations.CreateModel(
            name='NAICS_CLASSIFICATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_NAICS_Classification', models.CharField(max_length=20)),
                ('Clean_tech', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project')),
            ],
        ),
        migrations.CreateModel(
            name='FUNDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funder', models.CharField(max_length=20)),
                ('Funding_Level', models.CharField(max_length=40)),
                ('Project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project')),
            ],
        ),
        migrations.CreateModel(
            name='FINANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funding_for_projects_Admin', models.IntegerField()),
                ('Approved_industry_Partner_cash_Contribution', models.IntegerField()),
                ('Approved_industry_partner_In_Kind_contribution', models.IntegerField()),
                ('Funding_org_Roll_up', models.CharField(max_length=20)),
                ('Grant_Number', models.CharField(max_length=20)),
                ('Project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC_Finance.project')),
            ],
        ),
    ]
