# Generated by Django 3.2.13 on 2022-09-20 19:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('contactName', models.CharField(max_length=30)),
                ('contactDesignation', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('incorporationYear', models.IntegerField()),
                ('businessNumber', models.IntegerField()),
                ('numberOfEmployees', models.IntegerField()),
                ('coreOperations', models.CharField(max_length=100)),
                ('revenue', models.FloatField()),
                ('potentialProjects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectDescription', models.TextField()),
                ('noveltyProject', models.TextField()),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIHUB.companyinformation')),
            ],
        ),
    ]
