# Generated by Django 3.2.13 on 2022-09-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0002_companyinformation_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIHUB.projecttitle')),
            ],
        ),
    ]
