# Generated by Django 3.2.13 on 2022-10-14 20:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0005_alter_user_accounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectinfoPI',
            fields=[
                ('projectTitle', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('projectDescription', models.TextField()),
                ('projectobjectives', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('modeofdelivery', models.CharField(blank=True, max_length=100, null=True)),
                ('rf_initiation_risk', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_initiation_mitigation', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_implementation_risk', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_implementation_mitigation', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_execution_risk', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_execution_mitigation', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_commercialization_risk', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_commercialization_mitigation', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_sbe_risk', models.CharField(blank=True, max_length=1000, null=True)),
                ('rf_sbe_mitigation', models.CharField(blank=True, max_length=1000, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AIHUB.projecttitle')),
            ],
        ),
        migrations.CreateModel(
            name='workPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('projectTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIHUB.projectinfopi')),
            ],
        ),
        migrations.CreateModel(
            name='teamexperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('projectTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIHUB.projectinfopi')),
            ],
        ),
    ]
