# Generated by Django 3.2.13 on 2022-11-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0006_projectinfopi_teamexperts_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='files',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='Files/'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='status',
            field=models.CharField(blank=True, default='screening', max_length=50, null=True),
        ),
    ]
