# Generated by Django 3.2.13 on 2022-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0007_auto_20221107_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
