# Generated by Django 3.2.13 on 2022-11-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIHUB', '0008_companyinformation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttitle',
            name='status',
            field=models.CharField(blank=True, default='prospect', max_length=50),
        ),
    ]
